name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip<=24.2
  - pip:
    - dagshub==0.5.1
    - mlflow==2.19.0
    - numpy
    - pandas
    - scikit-learn
    - google-auth
    - google-auth-oauthlib
    - google-auth-httplib2
    - google-api-python-client
    - matplotlib
    - seaborn
